version: '3.8'
services:
  suprnews:
    build: .
    container_name: suprnews
    ports:
      - "8080:8080"
    volumes:
      - suprnews_data:/app/data
    restart: unless-stopped
    environment:
      - TZ=UTC
volumes:
  suprnews_data:
